
services:
  scoring-api:
    container_name: scoring-api
    image: scoring-api
    build:
      context: .
      dockerfile: ScoringAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5029:5029"
         
  scoring-api-dapr:
    container_name: scoring-api-dapr
    image: daprio/daprd:1.12.0
    network_mode: "service:scoring-api"
    command: ["./daprd",
               "-app-id", "scoring-api",
               "-app-port", "5029",
               "-components-path", "/components",
               "-config", "/configuration/zipkin.yaml"]
    depends_on: 
      - scoring-api
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
      - "./documents/:/tmp" # path in the host
  