apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: zipkin
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://host.docker.internal:9414/api/v2/spans
  metrics:
    enabled: true
